export interface KeycodeInfo {
  page: number;
  id: number;
  name: string;
  label: string;
  description?: string;
}

export const KEYCODE_CATEGORIES = [
  "Letters",
  "Numbers",
  "Symbols",
  "F-Keys",
  "Navigation",
  "Editing",
  "Numpad",
  "Modifiers",
  "Media",
  "Volume",
  "System",
  "Other",
];

export const CATEGORIZED_KEYCODES: Record<string, KeycodeInfo[]> = {
  Letters: [
    { page: 7, id: 0x04, name: "A", label: "A", description: "keycode.desc.a" },
    { page: 7, id: 0x05, name: "B", label: "B", description: "keycode.desc.b" },
    { page: 7, id: 0x06, name: "C", label: "C", description: "keycode.desc.c" },
    { page: 7, id: 0x07, name: "D", label: "D", description: "keycode.desc.d" },
    { page: 7, id: 0x08, name: "E", label: "E", description: "keycode.desc.e" },
    { page: 7, id: 0x09, name: "F", label: "F", description: "keycode.desc.f" },
    { page: 7, id: 0x0a, name: "G", label: "G", description: "keycode.desc.g" },
    { page: 7, id: 0x0b, name: "H", label: "H", description: "keycode.desc.h" },
    { page: 7, id: 0x0c, name: "I", label: "I", description: "keycode.desc.i" },
    { page: 7, id: 0x0d, name: "J", label: "J", description: "keycode.desc.j" },
    { page: 7, id: 0x0e, name: "K", label: "K", description: "keycode.desc.k" },
    { page: 7, id: 0x0f, name: "L", label: "L", description: "keycode.desc.l" },
    { page: 7, id: 0x10, name: "M", label: "M", description: "keycode.desc.m" },
    { page: 7, id: 0x11, name: "N", label: "N", description: "keycode.desc.n" },
    { page: 7, id: 0x12, name: "O", label: "O", description: "keycode.desc.o" },
    { page: 7, id: 0x13, name: "P", label: "P", description: "keycode.desc.p" },
    { page: 7, id: 0x14, name: "Q", label: "Q", description: "keycode.desc.q" },
    { page: 7, id: 0x15, name: "R", label: "R", description: "keycode.desc.r" },
    { page: 7, id: 0x16, name: "S", label: "S", description: "keycode.desc.s" },
    { page: 7, id: 0x17, name: "T", label: "T", description: "keycode.desc.t" },
    { page: 7, id: 0x18, name: "U", label: "U", description: "keycode.desc.u" },
    { page: 7, id: 0x19, name: "V", label: "V", description: "keycode.desc.v" },
    { page: 7, id: 0x1a, name: "W", label: "W", description: "keycode.desc.w" },
    { page: 7, id: 0x1b, name: "X", label: "X", description: "keycode.desc.x" },
    { page: 7, id: 0x1c, name: "Y", label: "Y", description: "keycode.desc.y" },
    { page: 7, id: 0x1d, name: "Z", label: "Z", description: "keycode.desc.z" },
  ],
  Numbers: [
    { page: 7, id: 0x1e, name: "1", label: "1", description: "keycode.desc.1" },
    { page: 7, id: 0x1f, name: "2", label: "2", description: "keycode.desc.2" },
    { page: 7, id: 0x20, name: "3", label: "3", description: "keycode.desc.3" },
    { page: 7, id: 0x21, name: "4", label: "4", description: "keycode.desc.4" },
    { page: 7, id: 0x22, name: "5", label: "5", description: "keycode.desc.5" },
    { page: 7, id: 0x23, name: "6", label: "6", description: "keycode.desc.6" },
    { page: 7, id: 0x24, name: "7", label: "7", description: "keycode.desc.7" },
    { page: 7, id: 0x25, name: "8", label: "8", description: "keycode.desc.8" },
    { page: 7, id: 0x26, name: "9", label: "9", description: "keycode.desc.9" },
    { page: 7, id: 0x27, name: "0", label: "0", description: "keycode.desc.0" },
  ],
  Symbols: [
    { page: 7, id: 0x2d, name: "Minus", label: "-", description: "keycode.desc.minus" },
    { page: 7, id: 0x2e, name: "Equal", label: "=", description: "keycode.desc.equal" },
    { page: 7, id: 0x2f, name: "Left Bracket", label: "[", description: "keycode.desc.lbracket" },
    { page: 7, id: 0x30, name: "Right Bracket", label: "]", description: "keycode.desc.rbracket" },
    { page: 7, id: 0x31, name: "Backslash", label: "\\", description: "keycode.desc.backslash" },
    { page: 7, id: 0x33, name: "Semicolon", label: ";", description: "keycode.desc.semicolon" },
    { page: 7, id: 0x34, name: "Quote", label: "'", description: "keycode.desc.quote" },
    { page: 7, id: 0x35, name: "Grave", label: "`", description: "keycode.desc.grave" },
    { page: 7, id: 0x36, name: "Comma", label: ",", description: "keycode.desc.comma" },
    { page: 7, id: 0x37, name: "Period", label: ".", description: "keycode.desc.period" },
    { page: 7, id: 0x38, name: "Slash", label: "/", description: "keycode.desc.slash" },
  ],
  "F-Keys": [
    { page: 7, id: 0x3a, name: "F1", label: "F1", description: "keycode.desc.f1" },
    { page: 7, id: 0x3b, name: "F2", label: "F2", description: "keycode.desc.f2" },
    { page: 7, id: 0x3c, name: "F3", label: "F3", description: "keycode.desc.f3" },
    { page: 7, id: 0x3d, name: "F4", label: "F4", description: "keycode.desc.f4" },
    { page: 7, id: 0x3e, name: "F5", label: "F5", description: "keycode.desc.f5" },
    { page: 7, id: 0x3f, name: "F6", label: "F6", description: "keycode.desc.f6" },
    { page: 7, id: 0x40, name: "F7", label: "F7", description: "keycode.desc.f7" },
    { page: 7, id: 0x41, name: "F8", label: "F8", description: "keycode.desc.f8" },
    { page: 7, id: 0x42, name: "F9", label: "F9", description: "keycode.desc.f9" },
    { page: 7, id: 0x43, name: "F10", label: "F10", description: "keycode.desc.f10" },
    { page: 7, id: 0x44, name: "F11", label: "F11", description: "keycode.desc.f11" },
    { page: 7, id: 0x45, name: "F12", label: "F12", description: "keycode.desc.f12" },
  ],
  Navigation: [
    { page: 7, id: 0x4f, name: "Right", label: "→", description: "keycode.desc.right" },
    { page: 7, id: 0x50, name: "Left", label: "←", description: "keycode.desc.left" },
    { page: 7, id: 0x51, name: "Down", label: "↓", description: "keycode.desc.down" },
    { page: 7, id: 0x52, name: "Up", label: "↑", description: "keycode.desc.up" },
    { page: 7, id: 0x4a, name: "Home", label: "Home", description: "keycode.desc.home" },
    { page: 7, id: 0x4d, name: "End", label: "End", description: "keycode.desc.end" },
    { page: 7, id: 0x4b, name: "Page Up", label: "PgUp", description: "keycode.desc.pgup" },
    { page: 7, id: 0x4e, name: "Page Down", label: "PgDn", description: "keycode.desc.pgdn" },
    { page: 7, id: 0x49, name: "Insert", label: "Ins", description: "keycode.desc.insert" },
    { page: 7, id: 0x4c, name: "Delete", label: "Del", description: "keycode.desc.delete" },
  ],
  Editing: [
    { page: 7, id: 0x28, name: "Enter", label: "Enter", description: "keycode.desc.enter" },
    { page: 7, id: 0x29, name: "Escape", label: "Esc", description: "keycode.desc.escape" },
    { page: 7, id: 0x2a, name: "Backspace", label: "BS", description: "keycode.desc.backspace" },
    { page: 7, id: 0x2b, name: "Tab", label: "Tab", description: "keycode.desc.tab" },
    { page: 7, id: 0x2c, name: "Space", label: "Space", description: "keycode.desc.space" },
    { page: 7, id: 0x39, name: "Caps Lock", label: "Caps", description: "keycode.desc.caps" },
    { page: 7, id: 0x46, name: "Print Screen", label: "PrtSc", description: "keycode.desc.prtsc" },
    { page: 7, id: 0x47, name: "Scroll Lock", label: "ScLock", description: "keycode.desc.sclock" },
    { page: 7, id: 0x48, name: "Pause", label: "Pause", description: "keycode.desc.pause" },
  ],
  Numpad: [
    { page: 7, id: 0x53, name: "Num Lock", label: "Num", description: "keycode.desc.numlock" },
    { page: 7, id: 0x54, name: "KP Divide", label: "/", description: "keycode.desc.kp_divide" },
    { page: 7, id: 0x55, name: "KP Multiply", label: "*", description: "keycode.desc.kp_multiply" },
    { page: 7, id: 0x56, name: "KP Minus", label: "-", description: "keycode.desc.kp_minus" },
    { page: 7, id: 0x57, name: "KP Plus", label: "+", description: "keycode.desc.kp_plus" },
    { page: 7, id: 0x58, name: "KP Enter", label: "Enter", description: "keycode.desc.kp_enter" },
    { page: 7, id: 0x59, name: "KP 1", label: "1", description: "keycode.desc.kp_1" },
    { page: 7, id: 0x5a, name: "KP 2", label: "2", description: "keycode.desc.kp_2" },
    { page: 7, id: 0x5b, name: "KP 3", label: "3", description: "keycode.desc.kp_3" },
    { page: 7, id: 0x5c, name: "KP 4", label: "4", description: "keycode.desc.kp_4" },
    { page: 7, id: 0x5d, name: "KP 5", label: "5", description: "keycode.desc.kp_5" },
    { page: 7, id: 0x5e, name: "KP 6", label: "6", description: "keycode.desc.kp_6" },
    { page: 7, id: 0x5f, name: "KP 7", label: "7", description: "keycode.desc.kp_7" },
    { page: 7, id: 0x60, name: "KP 8", label: "8", description: "keycode.desc.kp_8" },
    { page: 7, id: 0x61, name: "KP 9", label: "9", description: "keycode.desc.kp_9" },
    { page: 7, id: 0x62, name: "KP 0", label: "0", description: "keycode.desc.kp_0" },
    { page: 7, id: 0x63, name: "KP Dot", label: ".", description: "keycode.desc.kp_dot" },
  ],
  Modifiers: [
    { page: 7, id: 0xe0, name: "Left Control", label: "LCtrl", description: "keycode.desc.lctrl" },
    { page: 7, id: 0xe1, name: "Left Shift", label: "LShift", description: "keycode.desc.lshift" },
    { page: 7, id: 0xe2, name: "Left Alt", label: "LAlt", description: "keycode.desc.lalt" },
    { page: 7, id: 0xe3, name: "Left GUI", label: "LGUI", description: "keycode.desc.lgui" },
    { page: 7, id: 0xe4, name: "Right Control", label: "RCtrl", description: "keycode.desc.rctrl" },
    { page: 7, id: 0xe5, name: "Right Shift", label: "RShift", description: "keycode.desc.rshift" },
    { page: 7, id: 0xe6, name: "Right Alt", label: "RAlt", description: "keycode.desc.ralt" },
    { page: 7, id: 0xe7, name: "Right GUI", label: "RGUI", description: "keycode.desc.rgui" },
  ],
  Media: [
    { page: 12, id: 0xb0, name: "Play", label: "Play", description: "keycode.desc.play" },
    { page: 12, id: 0xb1, name: "Pause", label: "Pause", description: "keycode.desc.pause_media" },
    { page: 12, id: 0xb5, name: "Next", label: "Next", description: "keycode.desc.next" },
    { page: 12, id: 0xb6, name: "Previous", label: "Prev", description: "keycode.desc.prev" },
    { page: 12, id: 0xb7, name: "Stop", label: "Stop", description: "keycode.desc.stop" },
    { page: 12, id: 0xcd, name: "Play/Pause", label: "PP", description: "keycode.desc.play_pause" },
  ],
  Volume: [
    { page: 12, id: 0xe9, name: "Volume Up", label: "Vol+", description: "keycode.desc.vol_up" },
    { page: 12, id: 0xea, name: "Volume Down", label: "Vol-", description: "keycode.desc.vol_down" },
    { page: 12, id: 0xe2, name: "Mute", label: "Mute", description: "keycode.desc.mute" },
  ],
  System: [
    { page: 1, id: 0x81, name: "System Power Down", label: "Power", description: "keycode.desc.power" },
    { page: 1, id: 0x82, name: "System Sleep", label: "Sleep", description: "keycode.desc.sleep" },
    { page: 1, id: 0x83, name: "System Wake Up", label: "Wake", description: "keycode.desc.wake" },
  ]
};
